require("root.core.options")
require("root.core.keymaps")
require("root.core.quickfix")
require("root.core.run_code")
require("root.core.debug_code")
require("root.core.build_code")
require("root.core.make")
